table index polish
open-telemetry/docs-cn pull request #31
Opened 2021-01-06 16:09 UTC by tydhot

为已经翻译好的文档添加md跳转 并修复一些错误的跳转链接 修改overview与glossary文件的位置与项目一致

2021-01-06 16:34 UTC, WPH95 requested changes
有一些应该是 api.md 自身 title 的问题

2021-01-06 16:34 UTC, WPH95 commented on specification/glossary.md
> +一条嵌入在 Span 对象中，[Events](trace/api.md#-add-events) 列表中的 Log Record。
这个看起来很奇怪 - 作为开头 应该是 api.md 自身 title 多了一个空格

2021-01-06 16:34 UTC, WPH95 commented on specification/overview.md
> +- `TextMapPropagator`可以将值注入文本，也可以从文本当中提取值
中英文间空格

2021-01-06 16:34 UTC, WPH95 commented on specification/trace/api.md
> +  * [TracerProvider 操作](#tracerprovider-)
看起来奇怪

2021-01-06 18:02 UTC, tydhot commented on specification/trace/api.md
> +  * [TracerProvider 操作](#tracerprovider-)
是的 idea md插件的自动补全感觉不太对 我还是改成完整的形式来

2021-01-11 00:35 UTC, sunface approved these changes

2021-01-11 00:36 UTC, merged