add git ignore & java guides link for cn infomation.
open-telemetry/docs-cn pull request #34
Opened 2021-01-07 11:20 UTC by chenmudu

2021-01-07 11:29 UTC, WPH95 approved these changes

2021-01-07 11:29 UTC, WPH95 requested changes

2021-01-07 11:29 UTC, WPH95 commented on README.md
> +    - [上手指南之Java相关](https://github.com/chenmudu/open-telemetry-java-guides)
```suggestion
    - [上手指南之 Java 相关](https://github.com/chenmudu/open-telemetry-java-guides)
```

2021-01-07 11:34 UTC, WPH95 commented
personally. I don't recommend accepting unofficial documents for doc-cn at this time

2021-01-07 11:42 UTC, tydhot commented
> personally. I don't recommend accepting unofficial documents for doc-cn at this time

I think there should be an index of related article  to put some unofficial documents

2021-01-07 13:15 UTC, chenmudu commented
> > personally. I don't recommend accepting unofficial documents for doc-cn at this time
> 
> I think there should be an index of related article to put some unofficial documents

Maybe these unofficial projects should have a citation and eye-catching list. I just want to provide some convenience for more people. Hope this is a good and sincere suggestion. thanks a lot.

2021-01-08 01:03 UTC, sunface commented
@WPH95 @tydhot 

From my perspective, there should be no difference between official and unofficial at early stage, we need to encourage more people to contribute :D

2021-01-08 02:29 UTC, GlowingRuby commented
> > personally. I don't recommend accepting unofficial documents for doc-cn at this time
> 
> I think there should be an index of related article to put some unofficial documents

I agree with that. Unofficial documents should be welcomed, but there should be a clear distinction between them and official documents.

2021-01-08 02:48 UTC, chenmudu commented
@sunface @WPH95 @GlowingRuby 

So, should we add a hands-on guide(cn eg. 上手指南) to the first-level list of read me file contents? Some related items should be listed in the second list, along with their source, language and whether they are official.(cn eg. Java指南(unofficial)).

Hope to reach a consensus with all as soon as possible. Thanks a lot.

2021-01-08 11:32 UTC, sunface approved these changes

2021-01-08 11:33 UTC, merged