polish trace/api.md
open-telemetry/docs-cn pull request #36
Opened 2021-01-09 07:12 UTC by GlowingRuby

2021-01-09 08:17 UTC, WPH95 requested changes
the simple typo style need change

2021-01-09 08:17 UTC, WPH95 commented on specification/trace/api.md
> +  (例如 `io.opentelemetry.contrib.mongodb`)，而不是 instrumented library 的.
👍
```suggestion
  (例如 `io.opentelemetry.contrib.mongodb`)，而不是 instrumented library 的标识.
```

2021-01-09 08:26 UTC, WPH95 approved these changes

2021-01-09 08:29 UTC, WPH95 commented on specification/trace/api.md
> +分析工具应当通过抑制它们因其他原因产生的错误来响应 `Ok` 状态。例如抑制嘈杂的404错误。
https://github.com/open-telemetry/opentelemetry-specification/issues/1068
spec 在 ga 后会删除该部分。因为他们自己也没说清为什么 分析工具会产生错误。你现在这个翻译比我之前好很多

2021-01-09 08:35 UTC, GlowingRuby commented on specification/trace/api.md
> +分析工具应当通过抑制它们因其他原因产生的错误来响应 `Ok` 状态。例如抑制嘈杂的404错误。
是的，没看懂他们想表达什么意思

2021-01-09 11:18 UTC, WPH95 commented on specification/trace/api.md
> +分析工具应当通过抑制它们因其他原因产生的错误来响应 `Ok` 状态。例如抑制嘈杂的404错误。
我的理解是这样的 
分析工具 catch 了到了一个我问题，他应当返回 Ok，而不是 throw 一个 404 出来。
换个不太恰当的比方
User -> App -> DB
DB 扔了一个 404，对 App 来说 应该是 200, 而不是继续 404

2021-01-11 00:34 UTC, sunface approved these changes

2021-01-11 00:35 UTC, merged