docs: specification/baggage/api.md 原文更新有较大变动, 更新其文档翻译
open-telemetry/docs-cn pull request #54
Opened 2021-03-09 02:28 UTC by hanjm

2021-03-09 05:59 UTC, WPH95 requested changes
总体看起来非常棒，没什么问题。有一些标点符号和空格混合使用的问题，需要统一风格。
// 标点符号有点多，我就在 comment 简答举了几个例子。
1. 如果句子中存在中文，建议统一使用全角符号。
2. 中文句子中的英文统一前后空格。

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +>[原文](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md)更新时间: 2021-02-04
look great

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +这里定义的函数是指一种与拥有代表整个 Baggage 的结构体或对象进行交互的方式。取决于语言习惯，语言 API 可能仅提供与 `Context` 交互的函数来实现这些函数。
有点绕口
一种可能的优化：取决于语言习惯，语言 API 可能仅实现与 `Context` 交互的函数。

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +- 用于`Baggage` 与上下文交互的函数
```suggestion
- 用于 `Baggage` 与上下文交互的函数
```

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +在没有安装 SDK 情况时，Baggage API 必须提供完整功能。这是为实现透明的跨进程 Baggage 传播所必须的。如果在 API 中安装了 Baggage 传播者，无论是否安装了 SDK，它都可以工作。
可能： Baggage API 必须在没有安装 SDK 的情况下，提供完整功能
原有句子主语后置一点点奇怪

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +Baggage API 必须提供一个函数用于记录名称/值中的值，该函数接受一个名称和一个值作为入参。返回一个带有新值 `Baggage` 的`上下文`。取决于语言习惯, 语言API可以使用构建者模式来从Builder构建出一个`Baggage`.
只是好奇，入参是一个比较常见公认的词嘛。
这里用输入，输入参数。感觉更贴切些。

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +Baggage API 必须提供一个函数用于记录名称/值中的值，该函数接受一个名称和一个值作为入参。返回一个带有新值 `Baggage` 的`上下文`。取决于语言习惯, 语言API可以使用构建者模式来从Builder构建出一个`Baggage`.
```suggestion
Baggage API 必须提供一个函数用于记录名称/值中的值，该函数接受一个名称和一个值作为入参。返回一个带有新值 `Baggage` 的`上下文`。取决于语言习惯，语言API可以使用构建者模式来从 Builder 构建出一个 `Baggage`.
```

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +`Metadata` 与名称/值对相关联的元数据。这应当是一个对一个没有具体语义的字符串的不透明包装。以便于未来的功能拓展。
一个对一个xxx
读起来怪怪的。 (只是感觉，也没想到有什么特别好的改进办法

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +为了删除名称/值对，Baggage API 必须提供一个函数，接收一个名称作为入参。返回一个新的上下文，该上下文不再包含所选名称。取决于语言习惯, 语言API可以使用构建者模式来从Builder构建出一个`Baggage`.
```suggestion
为了删除名称/值对，Baggage API 必须提供一个函数，接收一个名称作为入参。返回一个新的上下文，该上下文不再包含所选名称。取决于语言习惯，语言 API 可以使用构建者模式来从 Builder 构建出一个 `Baggage`。
```

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +此节定义所有与 [`Context`](../context/context.md) 交互的有关 Baggage API 的操作
```suggestion
此节定义所有与 [`Context`](../context/context.md) 交互的有关 Baggage API 的操作。
```

2021-03-09 05:59 UTC, WPH95 commented on specification/baggage/api.md
> +此API必须提供以下方法与 `Context` 实例交互.
```suggestion
此 API 必须提供以下方法与 `Context` 实例交互。
```

2021-03-09 11:24 UTC, hanjm commented on specification/baggage/api.md
> +Baggage API 必须提供一个函数用于记录名称/值中的值，该函数接受一个名称和一个值作为入参。返回一个带有新值 `Baggage` 的`上下文`。取决于语言习惯, 语言API可以使用构建者模式来从Builder构建出一个`Baggage`.
挺常见的， 搜了下维基百科里也有， 我改成输入参数吧 :) https://zh.wikipedia.org/wiki/%E5%8F%83%E6%95%B8_(%E7%A8%8B%E5%BC%8F%E8%A8%AD%E8%A8%88)#.E8.BC.B8.E5.87.BA.E5.8F.83.E6.95.B8

2021-03-09 11:27 UTC, hanjm commented on specification/baggage/api.md
> +`Metadata` 与名称/值对相关联的元数据。这应当是一个对一个没有具体语义的字符串的不透明包装。以便于未来的功能拓展。
去掉前面的“一个”如何？  这应当是对一个没有具体语义的字符串的不透明包装。

2021-03-09 11:31 UTC, hanjm commented
> 1. 如果句子中存在中文，建议统一使用全角符号。
> 2. 中文句子中的英文统一前后空格。

fixed.
@WPH95

2021-03-16 01:17 UTC, sunface approved these changes

2021-03-16 01:17 UTC, merged