增加 library-guidelines.md 和 library-layout.md 的翻译。并更新结构和 open-telemetry/opentelemetry-specification 保持一致
open-telemetry/docs-cn pull request #58
Opened 2021-03-23 07:28 UTC by owt5008137

RT
第一次提交翻译文档，如有规范问题还请指出。谢谢。

2021-03-23 07:39 UTC, tydhot commented on specification/library-layout.md
> +本目录包含可以用于管理context propagation和与metrics相关的标签的 Baggage API.
感觉中文英文句号没有统一，有些地方采用了中文有些地方英文

2021-03-23 07:49 UTC, owt5008137 commented on specification/library-layout.md
> +本目录包含可以用于管理context propagation和与metrics相关的标签的 Baggage API.
已修订

2021-03-23 14:41 UTC, WPH95 requested changes
有的中英文间加了空格，有的没有。
请统一格式，中文与英文间加一个空格

2021-03-23 14:41 UTC, WPH95 commented on specification/library-layout.md
> +# OpenTelemetry工程结构
```suggestion
# OpenTelemetry 工程结构

```

2021-03-23 14:41 UTC, WPH95 commented on specification/library-layout.md
> +本文档展示了OpenTelemetry项目的基本的工程结构布局。对于包结构仅展示通用的部分，对某个特定语言的包结构不做强制要求。
```suggestion
本文档展示了 OpenTelemetry 项目的基本的工程结构布局。对于包结构仅展示通用的部分，对某个特定语言的包结构不做强制要求。

```

2021-03-24 02:57 UTC, owt5008137 commented on specification/library-layout.md
> +本文档展示了OpenTelemetry项目的基本的工程结构布局。对于包结构仅展示通用的部分，对某个特定语言的包结构不做强制要求。
已修订。顺带看了下其他文档好像英文术语的单词都是首字母大写的？我也改成全部首字母大写了

2021-03-30 02:58 UTC, sunface approved these changes

2021-03-30 02:58 UTC, merged